const scenarios={
 static:{url:'https://demo.local/',handler:'static file',latency:'4 ms',status:'200 OK',explain:'Nginx 直接从 /var/www/site 读取 index.html。没有应用服务器参与，因此响应路径最短。',code:`server {\n  listen 80;\n  server_name demo.local;\n\n  root /var/www/site;\n  index index.html;\n\n  location / {\n    try_files $uri $uri/ /index.html;\n  }\n}`},
 proxy:{url:'https://demo.local/api/users',handler:'upstream api',latency:'18 ms',status:'200 OK',explain:'前缀 /api/ 命中后，请求被转发到应用服务；Host 与客户端地址一并传给上游。',code:`server {\n  listen 80;\n  server_name demo.local;\n\n  location /api/ {\n    proxy_pass http://127.0.0.1:3000/;\n    proxy_set_header Host $host;\n    proxy_set_header X-Real-IP $remote_addr;\n  }\n}`},
 balance:{url:'https://demo.local/api/orders',handler:'app_server 2',latency:'23 ms',status:'200 OK',explain:'请求以加权轮询方式分发。app_server_2 获得更多流量，失败请求会尝试健康节点。',code:`upstream app_cluster {\n  server app_server_1:3000 weight=1;\n  server app_server_2:3000 weight=2;\n  keepalive 32;\n}\n\nlocation /api/ {\n  proxy_pass http://app_cluster;\n  proxy_next_upstream error timeout;\n}`},
 cache:{url:'https://demo.local/assets/app.js',handler:'browser cache',latency:'1 ms',status:'304 NOT MODIFIED',explain:'带内容哈希的静态资源可以长期缓存；HTML 保持短缓存，确保用户及时拿到新入口。',code:`location /assets/ {\n  expires 1y;\n  add_header Cache-Control\n    "public, immutable";\n}\n\nlocation = /index.html {\n  expires -1;\n  add_header Cache-Control "no-cache";\n}`}
};
const code=document.querySelector('#configCode'),url=document.querySelector('#requestUrl'),explain=document.querySelector('#scenarioExplain'),response=document.querySelector('#responseBox'),state=document.querySelector('#serverState');let current='static';
function paintCode(text){code.innerHTML=text.replace(/(server|listen|server_name|root|index|location|try_files|upstream|proxy_pass|proxy_set_header|keepalive|proxy_next_upstream|expires|add_header)(?=\s)/g,'<span class="tok-key">$1</span>').replace(/(http:\/\/[^;\s]+|\/[^;\s{]*)/g,'<span class="tok-val">$1</span>')}
function load(name){current=name;const s=scenarios[name];paintCode(s.code);url.value=s.url;explain.textContent=s.explain;response.innerHTML=`<div><span>STATUS</span><b>${s.status}</b></div><div><span>HANDLER</span><b>${s.handler}</b></div><div><span>LATENCY</span><b>${s.latency}</b></div>`;document.querySelectorAll('.scenario-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.scenario===name))}
document.querySelectorAll('.scenario-tabs button').forEach(b=>b.onclick=()=>load(b.dataset.scenario));
document.querySelector('#sendRequest').onclick=()=>{state.textContent='● ROUTING';response.style.opacity='.35';setTimeout(()=>{load(current);state.textContent='● READY';response.style.opacity='1';mark('lab')},650)};
document.querySelector('#copyConfig').onclick=async e=>{await navigator.clipboard.writeText(scenarios[current].code);e.target.textContent='已复制';setTimeout(()=>e.target.textContent='复制配置',1200)};
const saved=new Set(JSON.parse(localStorage.getItem('nginx-progress')||'[]'));function mark(task){saved.add(task);localStorage.setItem('nginx-progress',JSON.stringify([...saved]));renderProgress()}function renderProgress(){document.querySelectorAll('.complete').forEach(b=>{const done=saved.has(b.dataset.task);b.classList.toggle('done',done);b.textContent=done?'✓ 已完成':'标记完成'});const pct=Math.round(saved.size/6*100);document.querySelector('#progressText').textContent=pct+'%';document.querySelector('#progressBar').style.width=pct+'%'}
document.querySelectorAll('.complete').forEach(b=>b.onclick=()=>mark(b.dataset.task));document.querySelectorAll('#answers button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#answers button').forEach(x=>x.classList.remove('correct','wrong'));const ok=b.dataset.correct==='true';b.classList.add(ok?'correct':'wrong');document.querySelector('#quizFeedback').textContent=ok?'正确：普通前缀匹配会选择最长的匹配项。':'再想想：比较两个匹配前缀的长度。';if(ok)mark('quiz')});document.querySelector('#resetProgress').onclick=()=>{saved.clear();localStorage.removeItem('nginx-progress');renderProgress()};load('static');renderProgress();
